# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build package for deploying to Lambda

on: workflow_dispatch

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
     run:
      working-directory: lambda

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Replace variables in db.ini with secrets
      shell: bash
      run: |
        while IFS= read -r line
        do
            key=$(echo $line | cut -d = -f 1)
            value=$(echo $line | cut -d = -f 2)
            echo ${key}
            sed -i "s/\${${key}}/${value}/" db.ini
        done <<< ${MONGO_SECRETS}
      env:
        MONGO_SECRETS: ${{ secrets.MONGO_SECRETS }}
    - name: Install dependencies
      run: pip install "pymongo[srv]" --target .
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: package
        path: lambda/
        retention-days: 1
